package com.springboot.springbootwebtutorial.dto;


import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.time.LocalDate;


// In DTO we can add certain validations and constraints that we want to apply on the data that we are receiving from the client.
// We put just the data that we want to send to the client and ignore like password etc.

//@Data ---> we don/t need all the methods that are generated by @Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class EmployeeDTO {

    Long id;
    String name;
    String email;
    Integer age;
    LocalDate dateOfJoining;
//    @JsonProperty("isActive")
    Boolean isActive; // we can give any name
}